# -*- coding: utf-8 -*-
"""SEPM Model Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_J7ariIOBUhCJqODH2XJMCrjLMycRhE
"""

import torch
from torch import nn

torch.__version__

device = "cuda" if torch.cuda.is_available() else "cpu"
device

import os

BASE_PATH = os.path.join("content", "drive", "MyDrive")

import zipfile

dataset_path_zip = os.path.join("/content/drive/MyDrive/sepm dataset.zip")
with zipfile.ZipFile(dataset_path_zip, 'r') as zip_ref:
    zip_ref.extractall('dataset')

BASE_DIR = os.path.join("content", "dataset")
dir_path = os.path.join("content", "dataset", "train")
for dirpath, dirnames, filenames in os.walk(dir_path):
    print(f"There are {len(dirnames)} directories and {len(filenames)} images in '{dirpath}'.")

import random
from PIL import Image
import glob

BASE_DIR = "dataset"
image_path = os.path.join(BASE_DIR, "train")
image_path_list = glob.glob(os.path.join(image_path, "*/*.jpg"))

random_image_path = random.choice(image_path_list)
image_class = os.path.basename(os.path.dirname(random_image_path))

img = Image.open(random_image_path)

print(f"Random image path: {random_image_path}")
print(f"Image class: {image_class}")
print(f"Image height: {img.height}")
print(f"Image width: {img.width}")
img

from torch import nn
from torchvision import transforms

manual_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

import torch
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

train_data = datasets.ImageFolder(
    root=os.path.join(BASE_DIR, "train"),
    transform=manual_transforms,
    target_transform=None
)

train_data.classes

train_data.class_to_idx

len(train_data)

img, label = train_data[0][0], train_data[0][1]
print(f"Image tensor:\n{img}")
print(f"Image shape: {img.shape}")
print(f"Image datatype: {img.dtype}")
print(f"Image label: {label}")
print(f"Label datatype: {type(label)}")

from torch.utils.data import dataloader

train_dataloader = DataLoader(
    dataset=train_data,
    batch_size=32,
    num_workers=1,
    shuffle=True
)

train_dataloader

img, label = next(iter(train_dataloader))
print(f"Image shape: {img.shape} -> [batch_size, color_channels, height, width]")
print(f"Label shape: {label.shape}")

import torchvision

weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT
weights

auto_transforms = weights.transforms()
auto_transforms

weights = torchvision.models.EfficientNet_B0_Weights.DEFAULT
model = torchvision.models.efficientnet_b0(weights=weights).to(device)

for param in model.features.parameters():
    param.requires_grad = False

output_shape = len(train_data.classes)

model.classifier = nn.Sequential(
    nn.Dropout(p=0.2, inplace=True),
    nn.Linear(
        in_features=1280,
        out_features=output_shape,
        bias=True
    )
).to(device)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

from tqdm import tqdm

epochs = 1

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    progress_bar = tqdm(
        train_dataloader,
        desc=f"Epoch {epoch+1}/{epochs}",
        leave=False
    )

    for batch_idx, (inputs, targets) in enumerate(progress_bar):
        inputs, targets = inputs.to(device), targets.to(device)

        optimizer.zero_grad()

        outputs = model(inputs)
        loss = loss_fn(outputs, targets)

        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        avg_loss = running_loss / (batch_idx + 1)

        # Update tqdm bar
        progress_bar.set_postfix({
            "batch_loss": f"{loss.item():.4f}",
            "avg_loss": f"{avg_loss:.4f}"
        })

    epoch_loss = running_loss / len(train_dataloader)

    print(f"\n✅ Epoch [{epoch+1}/{epochs}] completed | Avg Loss: {epoch_loss:.4f}")

torch.save(model.state_dict(), "veriface_v2.pth")

! pip install onnxscript

import torch

# Set model to evaluation mode
model.eval()

# Example input shape for MobileNet-like models
# (batch_size, channels, height, width)
dummy_input = torch.randn(1, 3, 224, 224).to(device)

# Export to ONNX
torch.onnx.export(
    model,
    dummy_input,
    "veriface_v2.onnx",
    export_params=True,
    opset_version=12,          # slightly newer, safer
    do_constant_folding=True,
    input_names=["input"],
    output_names=["output"],
    dynamic_axes={
        "input": {0: "batch_size"},
        "output": {0: "batch_size"}
    }
)

print("✅ Model exported successfully to veriface_v2.onnx")